const ImageButtonsActionTypes = {
    ADD_IMAGE_BUTTON_TO_REDUX : 'ADD_IMAGE_BUTTON_TO_REDUX',
    UPDATE_IMAGE_BUTTON : 'UPDATE_IMAGE_BUTTON',
    RESET_IMAGE_BUTTON_STATES : 'RESET_IMAGE_BUTTON_STATES',
}

export default ImageButtonsActionTypes